import React from 'react';
import image from './highlights/1(1).jpg';
import image2 from './highlights/1(2).jpg';
import image3 from './highlights/1(3).jpg';
import image4 from './highlights/1(4).jpg';
import image5 from './highlights/1(5).jpg';
import image6 from './highlights/1(6).jpg';
import image7 from './highlights/1(7).jpg';
import image8 from './highlights/KMH_4858.jpg';
import image9 from './highlights/KMH_4859.jpg';
import image10 from './highlights/KMH_4862.jpg';
import image11 from './highlights/KMH_4863.jpg';
import image12 from './highlights/KMH_4865.jpg';
import image13 from './highlights/KMH_4867.jpg';
import image14 from './highlights/KMH_4868.jpg';
import image15 from './highlights/KMH_4869.jpg';
import image16 from './highlights/KMH_4870.jpg';
import image17 from './highlights/KMH_4872.jpg';
import image18 from './highlights/KMH_4876.jpg';
import image19 from './highlights/KMH_4882.jpg';
import image20 from './highlights/KMH_4885.jpg';
import image21 from './highlights/KMH_4887.jpg';
import image22 from './highlights/KMH_4891.jpg';
import image23 from './highlights/KMH_4892.jpg';
import image24 from './highlights/KMH_4894.jpg';
import image25 from './highlights/KMH_4895.jpg';
import image26 from './highlights/KMH_4898.jpg';
import image27 from './highlights/KMH_4899.jpg';
import image28 from './highlights/KMH_4903.jpg';
import image29 from './highlights/KMH_4905.jpg';
import image30 from './highlights/KMH_4910.jpg';
import image31 from './highlights/KMH_4911.jpg';
import image32 from './highlights/KMH_4913.jpg';
import image33 from './highlights/KMH_4916.jpg';
import image34 from './highlights/KMH_4920.jpg';
import image35 from './highlights/KMH_4925.jpg';
import image36 from './highlights/KMH_4927.jpg';
import image37 from './highlights/KMH_4929.jpg';
import image38 from './highlights/KMH_4931.jpg';
import image39 from './highlights/KMH_4935.jpg';
import image40 from './highlights/KMH_4936.jpg';
import image41 from './highlights/KMH_4938.jpg';
import image42 from './highlights/KMH_4940.jpg';
import image43 from './highlights/KMH_4944.jpg';
import image44 from './highlights/KMH_4945.jpg';
import image45 from './highlights/KMH_4949.jpg';
import image46 from './highlights/KMH_4951.jpg';
import image47 from './highlights/KMH_4954.jpg';
import image48 from './highlights/KMH_4956.jpg';
import image49 from './highlights/KMH_4959.jpg';
import image50 from './highlights/KMH_4961.jpg';
import image51 from './highlights/KMH_4962.jpg';
import image52 from './highlights/KMH_4967.jpg';
import image53 from './highlights/KMH_4968.jpg';
import image54 from './highlights/KMH_4969.jpg';
import image55 from './highlights/KMH_4970.jpg';
import image56 from './highlights/KMH_4971.jpg';
import image57 from './highlights/KMH_4972.jpg';
import image58 from './highlights/KMH_4974.jpg';
import image59 from './highlights/KMH_4975.jpg';
import image60 from './highlights/KMH_4976.jpg';
import image61 from './highlights/KMH_4977.jpg';
import image62 from './highlights/KMH_4978.jpg';
import image63 from './highlights/KMH_4979.jpg';
import image64 from './highlights/KMH_4981.jpg';
import image65 from './highlights/KMH_4982.jpg';
import image66 from './highlights/KMH_4983.jpg';
import image67 from './highlights/KMH_4984.jpg';
import image68 from './highlights/KMH_4985.jpg';
import image69 from './highlights/KMH_4986.jpg';
import image70 from './highlights/KMH_4987.jpg';
import image71 from './highlights/KMH_4989.jpg';
import image72 from './highlights/KMH_4990.jpg';
import image73 from './highlights/KMH_5002.jpg';
import image74 from './highlights/KMH_5005.jpg';
import image75 from './highlights/KMH_5006.jpg';
import image76 from './highlights/KMH_5009.jpg';
import image77 from './highlights/KMH_5013.jpg';
import image78 from './highlights/KMH_5018.jpg';
import image79 from './highlights/KMH_5020.jpg';
import image80 from './highlights/KMH_5022.jpg';
import image81 from './highlights/KMH_5024.jpg';
import image82 from './highlights/KMH_5029.jpg';
import image83 from './highlights/KMH_5031.jpg';
import image84 from './highlights/KMH_5033.jpg';
import image85 from './highlights/KMH_5035.jpg';
import image86 from './highlights/KMH_5038.jpg';
import image87 from './highlights/KMH_5040.jpg';
import image88 from './highlights/KMH_5041.jpg';
import image89 from './highlights/KMH_5044.jpg';
import image90 from './highlights/KMH_5046.jpg';
import image91 from './highlights/KMH_5051.jpg';
import image92 from './highlights/KMH_5058.jpg';
import image93 from './highlights/KMH_5061.jpg';
import image94 from './highlights/KMH_5065.jpg';
import image95 from './highlights/KMH_5069.jpg';
import image96 from './highlights/KMH_5073.jpg';
import image97 from './highlights/KMH_5074-2.jpg';
import image98 from './highlights/KMH_5075.jpg';
import image99 from './highlights/KMH_5074.jpg';
import image100 from './highlights/KMH_5077.jpg';
import image101 from './highlights/KMH_5080.jpg';
import image102 from './highlights/KMH_5081.jpg';
import image103 from './highlights/KMH_5086.jpg';
import image104 from './highlights/KMH_5093.jpg';
import image105 from './highlights/KMH_5096.jpg';
import image106 from './highlights/KMH_5099.jpg';
import image107 from './highlights/KMH_5101.jpg';
import image108 from './highlights/KMH_5107.jpg';
import image109 from './highlights/KMH_5108.jpg';
import image110 from './highlights/KMH_5111.jpg';
import image111 from './highlights/KMH_5113.jpg';
import image112 from './highlights/KMH_5116.jpg';
import image113 from './highlights/KMH_5121.jpg';
import image114 from './highlights/KMH_5135.jpg';
import image115 from './highlights/KMH_5138.jpg';
import image116 from './highlights/KMH_5143.jpg';
import image117 from './highlights/KMH_5148.jpg';
import image118 from './highlights/KMH_5151.jpg';
import image119 from './highlights/KMH_5152.jpg';
import image120 from './highlights/KMH_5154.jpg';
import image121 from './highlights/KMH_5156.jpg';
import image122 from './highlights/KMH_5158.jpg';
import image123 from './highlights/KMH_5160.jpg';
import image124 from './highlights/KMH_5161.jpg';
import image125 from './highlights/KMH_5164.jpg';
import image126 from './highlights/KMH_5166.jpg';
import image127 from './highlights/KMH_5169.jpg';
import image128 from './highlights/KMH_5173.jpg';
import image129 from './highlights/KMH_5174.jpg';
import image130 from './highlights/KMH_5175.jpg';
import image131 from './highlights/KMH_5177.jpg';
import image132 from './highlights/KMH_5180.jpg';
import image133 from './highlights/KMH_5181.jpg';
import image134 from './highlights/KMH_5183.jpg';
import image135 from './highlights/KMH_5185.jpg';
import image136 from './highlights/KMH_5188.jpg';
import image137 from './highlights/KMH_5193.jpg';
import image138 from './highlights/KMH_5194.jpg';
import image139 from './highlights/KMH_5196.jpg';
import image140 from './highlights/KMH_5202.jpg';
import image141 from './highlights/KMH_5205.jpg';
import image142 from './highlights/KMH_5210.jpg';
import image143 from './highlights/KMH_5215.jpg';
import image144 from './highlights/KMH_5217.jpg';
import image145 from './highlights/KMH_5221.jpg';
import image146 from './highlights/KMH_5223.jpg';
import image147 from './highlights/KMH_5227.jpg';
import image148 from './highlights/KMH_5228.jpg';
import image149 from './highlights/KMH_5231.jpg';
import image150 from './highlights/KMH_5235.jpg';
import image151 from './highlights/KMH_5237.jpg';
import image152 from './highlights/KMH_5238.jpg';
import image153 from './highlights/KMH_5243.jpg';
import image154 from './highlights/KMH_5247.jpg';
import image155 from './highlights/KMH_5249.jpg';
import image156 from './highlights/KMH_5251.jpg';
import image157 from './highlights/KMH_5253.jpg';
import image158 from './highlights/KMH_5255.jpg';
import image159 from './highlights/KMH_5256.jpg';
import image160 from './highlights/KMH_5260.jpg';
import image161 from './highlights/KMH_5264.jpg';
import image163 from './highlights/KMH_5266.jpg';
import image164 from './highlights/KMH_5269.jpg';
import image165 from './highlights/KMH_5273.jpg';
import image166 from './highlights/KMH_5283.jpg';
import image167 from './highlights/KMH_5285.jpg';
import image168 from './highlights/KMH_5288.jpg';
import image169 from './highlights/KMH_5289.jpg';
import image170 from './highlights/KMH_5291.jpg';
import image171 from './highlights/KMH_5293.jpg';
import image173 from './highlights/KMH_5295.jpg';
import image174 from './highlights/KMH_5302.jpg';
import image175 from './highlights/KMH_5303.jpg';
import image176 from './highlights/KMH_5307.jpg';
import image177 from './highlights/KMH_5309.jpg';
import image178 from './highlights/KMH_5314.jpg';
import image179 from './highlights/KMH_5318.jpg';
import image180 from './highlights/KMH_5323.jpg';
import image181 from './highlights/KMH_5329.jpg';
import image182 from './highlights/KMH_5330.jpg';
import image183 from './highlights/KMH_5331.jpg';
import image184 from './highlights/KMH_5332.jpg';
import image185 from './highlights/KMH_5336.jpg';
import image186 from './highlights/KMH_5346.jpg';
import image187 from './highlights/KMH_5349.jpg';
import image188 from './highlights/KMH_5351.jpg';
import image189 from './highlights/KMH_5354.jpg';
import image190 from './highlights/KMH_5356.jpg';
import image191 from './highlights/KMH_5357.jpg';
import image192 from './highlights/KMH_5361.jpg';
import image193 from './highlights/KMH_5362.jpg';
import image194 from './highlights/KMH_5363.jpg';
import image195 from './highlights/KMH_5364.jpg';
import image196 from './highlights/KMH_5366.jpg';
import image197 from './highlights/KMH_5367.jpg';
import image198 from './highlights/KMH_5368.jpg';
import image199 from './highlights/KMH_5369.jpg';
import image200 from './highlights/KMH_5370.jpg';
import image201 from './highlights/KMH_5372.jpg';
import image202 from './highlights/KMH_5373.jpg';
import image203 from './highlights/KMH_5374.jpg';
import image204 from './highlights/KMH_5375.jpg';
import image205 from './highlights/KMH_5377.jpg';
import image206 from './highlights/KMH_5378.jpg';
import image207 from './highlights/KMH_5379.jpg';
import image208 from './highlights/KMH_5380.jpg';
import image209 from './highlights/KMH_5381.jpg';
import image210 from './highlights/KMH_5382.jpg';
import image211 from './highlights/KMH_5384.jpg';
import image212 from './highlights/KMH_5385.jpg';
import image213 from './highlights/KMH_5387.jpg';
import image214 from './highlights/KMH_5388.jpg';
import image215 from './highlights/KMH_5389.jpg';
import image216 from './highlights/KMH_5392.jpg';
import image217 from './highlights/KMH_5394.jpg';
import image218 from './highlights/KMH_5396.jpg';
import image219 from './highlights/KMH_5397.jpg';
import image220 from './highlights/KMH_5400.jpg';
import image221 from './highlights/KMH_5401.jpg';
import image222 from './highlights/KMH_5402.jpg';
import image223 from './highlights/KMH_5403.jpg';
import image224 from './highlights/KMH_5406.jpg';
import image225 from './highlights/KMH_5408.jpg';
import image226 from './highlights/KMH_5410.jpg';
import image227 from './highlights/KMH_5411.jpg';
import image228 from './highlights/KMH_5413.jpg';
import image229 from './highlights/KMH_5415.jpg';
import image230 from './highlights/KMH_5417.jpg';



function Gallery() {
  // Use require.context to get all the image files in a directory
  // const images = require.context('./highlights', true, /\.(png|jpe?g|svg|jpg)$/);

  return (
    <div className="row justify-content-center">
      <div col-md-4 my-3>
      <img src={image} alt="cover" />
      <img src={image2} alt="cover" />
      <img src={image3} alt="cover" />
      <img src={image4} alt="cover" />
      <img src={image5} alt="cover" />
      <img src={image6} alt="cover" />
      <img src={image7} alt="cover" />
      <img src={image8} alt="cover" />
      <img src={image9} alt="cover" />
      <img src={image10} alt="cover" />
      <img src={image11} alt="cover" />
      <img src={image12} alt="cover" />
      <img src={image13} alt="cover" />
      <img src={image14} alt="cover" />
      <img src={image15} alt="cover" />
      <img src={image16} alt="cover" />
      <img src={image17} alt="cover" />
      <img src={image18} alt="cover" />
      <img src={image19} alt="cover" />
      <img src={image20} alt="cover" />
      <img src={image21} alt="cover" />
      <img src={image22} alt="cover" />
      <img src={image23} alt="cover" />
      <img src={image24} alt="cover" />
      <img src={image25} alt="cover" />
      <img src={image26} alt="cover" />
      <img src={image27} alt="cover" />
      <img src={image28} alt="cover" />
      <img src={image29} alt="cover" />
      <img src={image30} alt="cover" />
      <img src={image31} alt="cover" />
      <img src={image32} alt="cover" />
      <img src={image33} alt="cover" />
      <img src={image34} alt="cover" />
      <img src={image35} alt="cover" />
      <img src={image36} alt="cover" />
      <img src={image37} alt="cover" />
      <img src={image38} alt="cover" />
      <img src={image39} alt="cover" />
      <img src={image40} alt="cover" />
      <img src={image41} alt="cover" />
      <img src={image42} alt="cover" />
      <img src={image43} alt="cover" />
      <img src={image44} alt="cover" />
      <img src={image45} alt="cover" />
      <img src={image46} alt="cover" />
      <img src={image47} alt="cover" />
      <img src={image48} alt="cover" />
      <img src={image49} alt="cover" />
      <img src={image50} alt="cover" />
      <img src={image51} alt="cover" />
      <img src={image52} alt="cover" />
      <img src={image53} alt="cover" />
      <img src={image54} alt="cover" />
      <img src={image55} alt="cover" />
      <img src={image56} alt="cover" />
      <img src={image57} alt="cover" />
      <img src={image58} alt="cover" />
      <img src={image59} alt="cover" />
      <img src={image60} alt="cover" />
      <img src={image61} alt="cover" />
      <img src={image62} alt="cover" />
      <img src={image63} alt="cover" />
      <img src={image64} alt="cover" />
      <img src={image65} alt="cover" />
      <img src={image66} alt="cover" />
      <img src={image67} alt="cover" />
      <img src={image68} alt="cover" />
      <img src={image69} alt="cover" />
      <img src={image70} alt="cover" />
      <img src={image71} alt="cover" />
      <img src={image72} alt="cover" />
      <img src={image73} alt="cover" />
      <img src={image74} alt="cover" />
      <img src={image75} alt="cover" />
      <img src={image76} alt="cover" />
      <img src={image77} alt="cover" />
      <img src={image78} alt="cover" />
      <img src={image79} alt="cover" />
      <img src={image80} alt="cover" />
      <img src={image81} alt="cover" />
      <img src={image82} alt="cover" />
      <img src={image83} alt="cover" />
      <img src={image84} alt="cover" />
      <img src={image85} alt="cover" />
      <img src={image86} alt="cover" />
      <img src={image87} alt="cover" />
      <img src={image88} alt="cover" />
      <img src={image89} alt="cover" />
      <img src={image90} alt="cover" />
      <img src={image91} alt="cover" />
      <img src={image92} alt="cover" />
      <img src={image93} alt="cover" />
      <img src={image94} alt="cover" />
      <img src={image95} alt="cover" />
      <img src={image96} alt="cover" />
      <img src={image97} alt="cover" />
      <img src={image98} alt="cover" />
      <img src={image99} alt="cover" />
      <img src={image100} alt="cover" />
      <img src={image101} alt="cover" />
      <img src={image102} alt="cover" />

      <img src={image103} alt="cover" />
      <img src={image104} alt="cover" />
      <img src={image105} alt="cover" />
      <img src={image106} alt="cover" />
      <img src={image107} alt="cover" />
      <img src={image108} alt="cover" />
      <img src={image109} alt="cover" />
      <img src={image110} alt="cover" />
      <img src={image111} alt="cover" />
      <img src={image112} alt="cover" />
      <img src={image113} alt="cover" />
      <img src={image114} alt="cover" />
      <img src={image115} alt="cover" />
      <img src={image116} alt="cover" />
      <img src={image117} alt="cover" />
      <img src={image118} alt="cover" />
      <img src={image119} alt="cover" />
      <img src={image120} alt="cover" />
      <img src={image121} alt="cover" />
      <img src={image122} alt="cover" />
      <img src={image123} alt="cover" />
      <img src={image124} alt="cover" />
      <img src={image125} alt="cover" />
      <img src={image126} alt="cover" />
      <img src={image127} alt="cover" />
      <img src={image128} alt="cover" />
      <img src={image129} alt="cover" />
      <img src={image130} alt="cover" />
      <img src={image131} alt="cover" />
      <img src={image132} alt="cover" />
      <img src={image133} alt="cover" />
      <img src={image134} alt="cover" />
      <img src={image135} alt="cover" />
      <img src={image136} alt="cover" />
      <img src={image137} alt="cover" />
      <img src={image138} alt="cover" />
      <img src={image139} alt="cover" />
      <img src={image140} alt="cover" />
      <img src={image141} alt="cover" />
      <img src={image142} alt="cover" />
      <img src={image143} alt="cover" />
      <img src={image144} alt="cover" />
      <img src={image145} alt="cover" />
      <img src={image146} alt="cover" />
      <img src={image147} alt="cover" />
      <img src={image148} alt="cover" />
      <img src={image149} alt="cover" />
      <img src={image150} alt="cover" />
      <img src={image151} alt="cover" />
      <img src={image152} alt="cover" />
      <img src={image153} alt="cover" />
      <img src={image154} alt="cover" />
      <img src={image155} alt="cover" />
      <img src={image156} alt="cover" />
      <img src={image157} alt="cover" />
      <img src={image158} alt="cover" />
      <img src={image159} alt="cover" />
      <img src={image160} alt="cover" />
      <img src={image161} alt="cover" />
      {/* <img src={image162} alt="cover" /> */}
      <img src={image163} alt="cover" />
      <img src={image164} alt="cover" />
      <img src={image165} alt="cover" />
      <img src={image166} alt="cover" />
      <img src={image167} alt="cover" />
      <img src={image168} alt="cover" />
      <img src={image169} alt="cover" />
      <img src={image170} alt="cover" />
      <img src={image171} alt="cover" />
      <img src={image173} alt="cover" />
      <img src={image174} alt="cover" />
      <img src={image175} alt="cover" />
      <img src={image176} alt="cover" />
      <img src={image177} alt="cover" />
      <img src={image178} alt="cover" />
      <img src={image179} alt="cover" />
      <img src={image180} alt="cover" />
      <img src={image181} alt="cover" />
      <img src={image182} alt="cover" />
      <img src={image183} alt="cover" />
      <img src={image184} alt="cover" />
      <img src={image185} alt="cover" />
      <img src={image186} alt="cover" />
      <img src={image187} alt="cover" />
      <img src={image188} alt="cover" />
      <img src={image189} alt="cover" />
      <img src={image190} alt="cover" />
      <img src={image192} alt="cover" />
      <img src={image191} alt="cover" />
      <img src={image193} alt="cover" />
      <img src={image194} alt="cover" />
      <img src={image195} alt="cover" />
      <img src={image196} alt="cover" />
      <img src={image197} alt="cover" />
      <img src={image198} alt="cover" />
      <img src={image199} alt="cover" />
      <img src={image200} alt="cover" />
      <img src={image201} alt="cover" />
      <img src={image202} alt="cover" />
      <img src={image203} alt="cover" />
      <img src={image204} alt="cover" />
      <img src={image205} alt="cover" />
      <img src={image206} alt="cover" />
      <img src={image207} alt="cover" />
      <img src={image208} alt="cover" />
      <img src={image209} alt="cover" />
      <img src={image210} alt="cover" />
      <img src={image211} alt="cover" />
      <img src={image212} alt="cover" />
      <img src={image213} alt="cover" />
      <img src={image214} alt="cover" />
      <img src={image215} alt="cover" />
      <img src={image216} alt="cover" />
      <img src={image217} alt="cover" />
      <img src={image218} alt="cover" />
      <img src={image219} alt="cover" />
      <img src={image220} alt="cover" />
      <img src={image221} alt="cover" />
      <img src={image222} alt="cover" />
      <img src={image223} alt="cover" />
      <img src={image224} alt="cover" />
      <img src={image225} alt="cover" />
      <img src={image226} alt="cover" />
      <img src={image227} alt="cover" />
      <img src={image228} alt="cover" />
      <img src={image229} alt="cover" />

      <img src={image230} alt="cover" />
      </div>
     














    
      {/* Use .keys() to get an array of all the image filenames */}
      {/* <div className="row justify-content-center">
        {images.keys().map((path, index) => {
          // Use the .default attribute for each image file to access the actual file path.
          let final_path = images(path).default;
          console.log(final_path);
          
          return (
            <div className="col-md-4 my-3" key={index}>
              <img src={final_path} alt={`Highlight ${index + 1}`} className="w-100" />
            </div>
          );
        })}
      </div> */}
    </div>
  );
}

export default Gallery;
